//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFood.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechFood.Common.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password..
        /// </summary>
        public static string Auth_InvalidUseOrPassword1 {
            get {
                return ResourceManager.GetString("Auth_InvalidUseOrPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category file image cannot be empty.
        /// </summary>
        public static string Category_ThrowFileImageIsEmpty {
            get {
                return ResourceManager.GetString("Category_ThrowFileImageIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category order must be greater than or equal to 0..
        /// </summary>
        public static string Category_ThrowIndexIsLessThanZero {
            get {
                return ResourceManager.GetString("Category_ThrowIndexIsLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name cannot be empty.
        /// </summary>
        public static string Category_ThrowNameIsEmpty {
            get {
                return ResourceManager.GetString("Category_ThrowNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document CPF is invalid.
        /// </summary>
        public static string Customer_ThrowDocumentCPFInvalid {
            get {
                return ResourceManager.GetString("Customer_ThrowDocumentCPFInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Invalid.
        /// </summary>
        public static string Customer_ThrowEmailInvalid {
            get {
                return ResourceManager.GetString("Customer_ThrowEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name and image file name cannot be null or empty..
        /// </summary>
        public static string ImageUrlResolver_FolderCannotBeNull {
            get {
                return ResourceManager.GetString("ImageUrlResolver_FolderCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount is not equal to the order total amount..
        /// </summary>
        public static string Order_AmountIsNotEqualOrderAmount {
            get {
                return ResourceManager.GetString("Order_AmountIsNotEqualOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add items to an order that is not in the Created status..
        /// </summary>
        public static string Order_CannotAddItemToNonCreatedStatus {
            get {
                return ResourceManager.GetString("Order_CannotAddItemToNonCreatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply discount to an order that is not in the Created status..
        /// </summary>
        public static string Order_CannotApplyDiscountToNonCreatedStatus {
            get {
                return ResourceManager.GetString("Order_CannotApplyDiscountToNonCreatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a payment for an order that is not in the Created status..
        /// </summary>
        public static string Order_CannotCreatePaymentToNonCreatedStatus {
            get {
                return ResourceManager.GetString("Order_CannotCreatePaymentToNonCreatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot done an order that is not in the InPreparation status..
        /// </summary>
        public static string Order_CannotFinishToNonInPreparationStatus {
            get {
                return ResourceManager.GetString("Order_CannotFinishToNonInPreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pay for an order that is not in the Waiting Payment status..
        /// </summary>
        public static string Order_CannotPayToNonWaitingPaymentStatus {
            get {
                return ResourceManager.GetString("Order_CannotPayToNonWaitingPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot prepare an order that is not in the Paid status..
        /// </summary>
        public static string Order_CannotPrepareToNonPaidStatus {
            get {
                return ResourceManager.GetString("Order_CannotPrepareToNonPaidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refuse payment for an order that is not in the Waiting Payment status..
        /// </summary>
        public static string Order_CannotRefuseToNonWaitingPaymentStatus {
            get {
                return ResourceManager.GetString("Order_CannotRefuseToNonWaitingPaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove items from an order that is not in the Created status..
        /// </summary>
        public static string Order_CannotRemoveItemToNonCreatedStatus {
            get {
                return ResourceManager.GetString("Order_CannotRemoveItemToNonCreatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cannot be negative..
        /// </summary>
        public static string Order_DiscountCannotBeNegative {
            get {
                return ResourceManager.GetString("Order_DiscountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item not found..
        /// </summary>
        public static string Order_ItemNotFound {
            get {
                return ResourceManager.GetString("Order_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Found.
        /// </summary>
        public static string Order_ItemNotFound1 {
            get {
                return ResourceManager.GetString("Order_ItemNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string Order_OrderNotFound {
            get {
                return ResourceManager.GetString("Order_OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment cannot be null..
        /// </summary>
        public static string Order_PaymentIsNull {
            get {
                return ResourceManager.GetString("Order_PaymentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProductId is not valid.
        /// </summary>
        public static string OrderItem_ThrowProductIdIsInvalid {
            get {
                return ResourceManager.GetString("OrderItem_ThrowProductIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OrdemItem quantity have be greater than zero.
        /// </summary>
        public static string OrderItem_ThrowQuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("OrderItem_ThrowQuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The orderItem UnitPrice have be greater than zero.
        /// </summary>
        public static string OrderItem_ThrowUnitPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("OrderItem_ThrowUnitPriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has already been paid..
        /// </summary>
        public static string Payment_AlreadyPaid {
            get {
                return ResourceManager.GetString("Payment_AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Not Found.
        /// </summary>
        public static string Product_CaregoryNotFound {
            get {
                return ResourceManager.GetString("Product_CaregoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Not Found.
        /// </summary>
        public static string Product_ProductNotFound {
            get {
                return ResourceManager.GetString("Product_ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product CategoryId is not valid.
        /// </summary>
        public static string Product_ThrowCategoryIdInvalid {
            get {
                return ResourceManager.GetString("Product_ThrowCategoryIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category image file cannot be empty.
        /// </summary>
        public static string Product_ThrowCategoryImageFileIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowCategoryImageFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product description cannot be empty.
        /// </summary>
        public static string Product_ThrowDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name cannot empty .
        /// </summary>
        public static string Product_ThrowNameIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product price cannot be empty.
        /// </summary>
        public static string Product_ThrowPriceIsGreaterThanZero {
            get {
                return ResourceManager.GetString("Product_ThrowPriceIsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password hash cannot be empty.
        /// </summary>
        public static string User_PasswordHashIsEmpty {
            get {
                return ResourceManager.GetString("User_PasswordHashIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name cannot be empty.
        /// </summary>
        public static string User_RoleIsEmpty {
            get {
                return ResourceManager.GetString("User_RoleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command state is not valid for the current request..
        /// </summary>
        public static string ValidationException_Message {
            get {
                return ResourceManager.GetString("ValidationException_Message", resourceCulture);
            }
        }
    }
}
