apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: techfood

resources:
  - ../../base

patchesStrategicMerge:
  - development-patches.yaml

commonLabels:
  environment: development
