apiVersion: v1
kind: ConfigMap
metadata:
  name: techfood-api-config
  namespace: techfood
  labels:
    app.kubernetes.io/name: techfood-api
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: techfood-system
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  TechFoodStaticImagesUrl: "/static-images"
  AllowedHosts: "*"
  Jwt__Issuer: "techfood-jwts"
  Jwt__Audience: "techfood"
  Payments__MercadoPago__UserId: "2414323212"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: techfood
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: techfood-system
data:
  default.conf: |
    upstream admin_upstream {
        server techfood-admin-service:80;
    }

    upstream self_order_upstream {
        server techfood-self-order-service:80;
    }

    upstream monitor_upstream {
        server techfood-monitor-service:80;
    }

    upstream api_upstream {
        server techfood-api-service:8080;
    }

    server {
        listen 30000;

        port_in_redirect on;

        proxy_http_version 1.1;
        
        # Root location - redirect to admin
        location = / {
            return 301 /admin/;
        }
        
        # Admin application
        location /admin/ {
            proxy_pass http://admin_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /admin {
            return 301 /admin/;
        }
        
        # Self-Order application
        location /self-order/ {
            proxy_pass http://self_order_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /self-order {
            return 301 /self-order/;
        }
        
        # Monitor application
        location /monitor/ {
            proxy_pass http://monitor_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /monitor {
            return 301 /monitor/;
        }
        
        # API endpoints
        location /api/ {
            proxy_pass http://api_upstream/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix /api;
        }
        
        location /api {
            return 301 /api/;
        }

        location /health/ {
            proxy_pass http://api_upstream/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            return 301 /health/;
        }
    }
