apiVersion: apps/v1
kind: Deployment
metadata:
  name: techfood-nginx
  namespace: techfood
  labels:
    app.kubernetes.io/name: techfood-nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: techfood-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: techfood-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: techfood-nginx
        app.kubernetes.io/component: proxy
        app.kubernetes.io/part-of: techfood-system
    spec:
      containers:
        - name: nginx
          image: techfood.nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 30000
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 30000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 30000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: techfood-nginx-service
  namespace: techfood
  labels:
    app.kubernetes.io/name: techfood-nginx
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: techfood-system
spec:
  ports:
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app.kubernetes.io/name: techfood-nginx
  type: NodePort
